/**
 * Command icons: Lucide (https://lucide.dev), ISC license. A few icons derive from
 * Feather (MIT). They are bundled as tree-shaken icon nodes from the `lucide` package,
 * with no network loading. These are original line icons, not Microsoft Office artwork. See NOTICE.
 *
 * Lookup order: exact command id (ICON_BY_ID), then the command slug (ICON_BY_SLUG).
 * Commands in TEXT_ONLY render as labelled fields or text buttons, with no icon.
 */
import {
  AArrowDown,
  AArrowUp,
  Accessibility,
  AlignCenterVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalSpaceAround,
  AlignVerticalJustifyCenter,
  AlignVerticalSpaceAround,
  AppWindow,
  AppWindowMac,
  ArrowDown,
  ArrowDownAZ,
  ArrowDownFromLine,
  ArrowDownNarrowWide,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUpFromLine,
  ArrowUpToLine,
  AudioLines,
  BadgeCheck,
  Baseline,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  Blend,
  Blocks,
  Bold,
  BookA,
  BookBookmark,
  BookOpen,
  BookOpenText,
  BookType,
  Bookmark,
  Box,
  Braces,
  BringToFront,
  Brush,
  CalendarClock,
  Captions,
  CaseSensitive,
  ChartColumn,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleDot,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardPaste,
  ClipboardPen,
  ClipboardType,
  Columns2,
  Columns3,
  Contact,
  Copy,
  Crop,
  Divide,
  Droplet,
  Equal,
  Eraser,
  Eye,
  EyeOff,
  File,
  FileBox,
  FileCog,
  FileDiff,
  FileDown,
  FileOutput,
  FilePlus,
  FileSymlink,
  FileText,
  Files,
  Focus,
  FoldVertical,
  FolderOpen,
  Frame,
  Gift,
  GitCompare,
  GitCompareArrows,
  GitMerge,
  Glasses,
  Globe,
  GraduationCap,
  Grid2x2,
  Grid2x2Check,
  Grid3x3,
  Group,
  Hand,
  HardDriveDownload,
  Hash,
  Highlighter,
  House,
  Image,
  ImageUp,
  Images,
  Infinity as InfinityIcon,
  Info,
  Italic,
  Languages,
  LassoSelect,
  Layers,
  LayoutGrid,
  LayoutPanelTop,
  Letters,
  Library,
  LifeBuoy,
  Link,
  Link2,
  List,
  ListChecks,
  ListChevronsUpDown,
  ListCollapse,
  ListFilter,
  ListIndentDecrease,
  ListIndentIncrease,
  ListOrdered,
  ListTree,
  Locate,
  Lock,
  Mail,
  Mails,
  Merge,
  MessageCircleHeart,
  MessageSquarePlus,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Minus,
  MousePointer2,
  Move,
  MoveHorizontal,
  MoveVertical,
  Network,
  NotebookText,
  NotepadText,
  Omega,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PaintbrushVertical,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelTop,
  Parentheses,
  Pen,
  PenLine,
  PenTool,
  PencilRuler,
  Pilcrow,
  Plus,
  Printer,
  Puzzle,
  Quote,
  Radical,
  RefreshCw,
  RemoveFormatting,
  Repeat,
  Replace,
  Rewind,
  RotateCcw,
  RotateCcwSquare,
  RotateCw,
  Rows2,
  Rows3,
  Ruler,
  RulerDimensionLine,
  Save,
  SaveAll,
  Scale,
  Scaling,
  ScanText,
  Scissors,
  ScreenShare,
  ScrollText,
  Search,
  Send,
  SendToBack,
  SeparatorHorizontal,
  Settings,
  Shapes,
  Share2,
  ShieldCheck,
  Shrink,
  Sigma,
  Signature,
  SlidersHorizontal,
  Sparkles,
  SpellCheck,
  SpellCheck2,
  Spline,
  Split,
  Square,
  SquareCode,
  SquareDashed,
  SquareDashedBottom,
  SquareFunction,
  Sticker,
  Strikethrough,
  Subscript,
  SunMedium,
  Superscript,
  SwatchBook,
  Table,
  Table2,
  TableCellsSplit,
  TableProperties,
  Tag,
  Tags,
  Telescope,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  TextCursor,
  TextCursorInput,
  TextInitial,
  TextWrap,
  Trash,
  Type,
  TypeOutline,
  Underline,
  UnfoldVertical,
  UserPen,
  UserSearch,
  UserX,
  Users,
  WandSparkles,
  WholeWord,
  X,
  ZoomIn,
  type IconNode,
} from 'lucide';

export type { IconNode };

/** Default icon per command slug (the last segment of the id). */
export const ICON_BY_SLUG: Readonly<Record<string, IconNode>> = {
  home: House,
  new: FilePlus,
  open: FolderOpen,
  info: Info,
  save: Save,
  'save-as': SaveAll,
  print: Printer,
  share: Share2,
  export: FileOutput,
  close: X,
  account: CircleUser,
  options: Settings,
  paste: ClipboardPaste,
  'paste-keep-source': ClipboardCheck,
  'paste-merge': ClipboardList,
  'paste-text-only': ClipboardType,
  'paste-special': ClipboardPen,
  cut: Scissors,
  copy: Copy,
  'format-painter': Paintbrush,
  grow: AArrowUp,
  shrink: AArrowDown,
  'change-case': CaseSensitive,
  'clear-formatting': RemoveFormatting,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  subscript: Subscript,
  superscript: Superscript,
  'text-effects': Sparkles,
  highlight: Highlighter,
  'font-color': Baseline,
  'font-dialog': Type,
  bullets: List,
  numbering: ListOrdered,
  'multilevel-list': ListTree,
  'decrease-indent': ListIndentDecrease,
  'increase-indent': ListIndentIncrease,
  sort: ArrowDownAZ,
  'show-marks': Pilcrow,
  'align-left': TextAlignStart,
  'align-center': TextAlignCenter,
  'align-right': TextAlignEnd,
  justify: TextAlignJustify,
  'line-spacing': ListChevronsUpDown,
  shading: PaintBucket,
  borders: SquareDashed,
  'paragraph-dialog': SlidersHorizontal,
  gallery: SwatchBook,
  'styles-pane': PanelRight,
  find: Search,
  replace: Replace,
  select: MousePointer2,
  dictate: Mic,
  editor: SpellCheck,
  'add-ins': Puzzle,
  'cover-page': BookOpen,
  'blank-page': File,
  'page-break': SeparatorHorizontal,
  table: Table,
  'draw-table': PencilRuler,
  'convert-text-to-table': TableProperties,
  'quick-tables': Table2,
  pictures: Image,
  shapes: Shapes,
  icons: Sticker,
  '3d-models': Box,
  smartart: Network,
  chart: ChartColumn,
  screenshot: ScreenShare,
  'get-add-ins': Puzzle,
  'online-video': Clapperboard,
  link: Link,
  bookmark: Bookmark,
  'cross-reference': Link2,
  comment: MessageSquarePlus,
  header: PanelTop,
  footer: PanelBottom,
  'page-number': Hash,
  'text-box': TextCursorInput,
  'quick-parts': Blocks,
  wordart: WandSparkles,
  'drop-cap': TextInitial,
  'signature-line': Signature,
  'date-time': CalendarClock,
  object: FileBox,
  equation: Sigma,
  symbol: Omega,
  lasso: LassoSelect,
  eraser: Eraser,
  pens: PenTool,
  'add-pen': PenLine,
  'draw-with-touch': Hand,
  'ink-to-shape': Shapes,
  'ink-to-math': SquareFunction,
  'drawing-canvas': Frame,
  'ink-replay': Rewind,
  themes: Palette,
  'style-set': SwatchBook,
  colors: PaintbrushVertical,
  fonts: Type,
  'paragraph-spacing': BetweenHorizontalStart,
  effects: Sparkles,
  'set-as-default': BadgeCheck,
  watermark: Droplet,
  'page-color': PaintBucket,
  'page-borders': SquareDashed,
  margins: SquareDashedBottom,
  orientation: RotateCcwSquare,
  size: RulerDimensionLine,
  columns: Columns2,
  breaks: BetweenVerticalStart,
  'line-numbers': ListOrdered,
  hyphenation: Minus,
  'indent-left': ListIndentIncrease,
  'indent-right': ListIndentDecrease,
  'spacing-before': ArrowUpToLine,
  'spacing-after': ArrowDownToLine,
  position: Move,
  'wrap-text': TextWrap,
  'bring-forward': BringToFront,
  'send-backward': SendToBack,
  'selection-pane': Layers,
  align: AlignHorizontalDistributeCenter,
  group: Group,
  rotate: RotateCw,
  'table-of-contents': ListTree,
  'add-text': TextCursor,
  'update-table': RefreshCw,
  'insert-footnote': Superscript,
  'insert-endnote': FileDown,
  'next-footnote': ArrowDownNarrowWide,
  'show-notes': NotebookText,
  researcher: Telescope,
  'insert-citation': Quote,
  'manage-sources': Library,
  style: BookType,
  bibliography: BookBookmark,
  'insert-caption': Captions,
  'table-of-figures': Images,
  'mark-entry': Tag,
  'insert-index': BookA,
  'update-index': RefreshCw,
  'mark-citation': Tags,
  'insert-toa': Scale,
  'update-toa': RefreshCw,
  envelopes: Mail,
  labels: Tag,
  start: Mails,
  'select-recipients': Users,
  'edit-recipient-list': UserPen,
  'highlight-merge-fields': Highlighter,
  'address-block': Contact,
  'greeting-line': Hand,
  'insert-merge-field': Braces,
  rules: ListChecks,
  'match-fields': GitCompareArrows,
  'update-labels': RefreshCw,
  preview: Eye,
  'first-record': ChevronsLeft,
  'previous-record': ChevronLeft,
  'go-to-record': Locate,
  'next-record': ChevronRight,
  'last-record': ChevronsRight,
  'find-recipient': UserSearch,
  'check-for-errors': ShieldCheck,
  'finish-merge': Send,
  'spelling-grammar': SpellCheck2,
  thesaurus: BookA,
  'word-count': WholeWord,
  rewrite: WandSparkles,
  'fix-grammar': SpellCheck,
  summarize: ScrollText,
  shorten: FoldVertical,
  expand: UnfoldVertical,
  'tell-lucid': MessageSquareText,
  'ai-models': HardDriveDownload,
  'read-aloud': AudioLines,
  'check-accessibility': Accessibility,
  translate: Languages,
  language: Globe,
  'new-comment': MessageSquarePlus,
  delete: Trash,
  previous: ArrowUp,
  next: ArrowDown,
  'show-comments': MessagesSquare,
  'track-changes': FileDiff,
  'display-for-review': Eye,
  'show-markup': ListFilter,
  'reviewing-pane': PanelLeft,
  accept: Check,
  reject: X,
  'previous-change': ArrowUpFromLine,
  'next-change': ArrowDownFromLine,
  compare: GitCompare,
  combine: GitMerge,
  'block-authors': UserX,
  'restrict-editing': Lock,
  'hide-ink': EyeOff,
  'read-mode': BookOpenText,
  'print-layout': FileText,
  'web-layout': Globe,
  outline: PenLine,
  draft: NotepadText,
  focus: Focus,
  'immersive-reader': Glasses,
  vertical: MoveVertical,
  'side-to-side': MoveHorizontal,
  ruler: Ruler,
  gridlines: Grid3x3,
  'navigation-pane': PanelLeft,
  zoom: ZoomIn,
  'one-page': File,
  'multiple-pages': Files,
  'page-width': MoveHorizontal,
  'new-window': AppWindow,
  'arrange-all': LayoutGrid,
  split: Rows2,
  'side-by-side': Columns2,
  'synchronous-scrolling': ArrowDownUp,
  'reset-window-position': RotateCcw,
  'switch-windows': AppWindowMac,
  macros: SquareCode,
  properties: FileCog,
  help: CircleQuestionMark,
  'contact-support': LifeBuoy,
  feedback: MessageCircleHeart,
  'show-training': GraduationCap,
  'whats-new': Gift,
  'header-row': PanelTop,
  'total-row': PanelBottom,
  'banded-rows': Rows3,
  'first-column': PanelLeft,
  'last-column': PanelRight,
  'banded-columns': Columns3,
  'border-styles': SquareDashed,
  'line-style': Minus,
  'line-weight': Equal,
  'pen-color': Pen,
  'border-painter': PaintRoller,
  'view-gridlines': Grid3x3,
  'insert-above': BetweenHorizontalStart,
  'insert-below': BetweenHorizontalEnd,
  'insert-left': BetweenVerticalStart,
  'insert-right': BetweenVerticalEnd,
  'merge-cells': Merge,
  'split-cells': Split,
  'split-table': TableCellsSplit,
  autofit: Scaling,
  height: MoveVertical,
  width: MoveHorizontal,
  'distribute-rows': AlignVerticalSpaceAround,
  'distribute-columns': AlignHorizontalSpaceAround,
  'cell-align': AlignCenterVertical,
  'text-direction': ArrowRightLeft,
  'cell-margins': SquareDashed,
  'repeat-header-rows': Repeat,
  'convert-to-text': Letters,
  formula: SquareFunction,
  'remove-background': Eraser,
  corrections: SunMedium,
  color: Palette,
  'artistic-effects': Brush,
  transparency: Blend,
  compress: Shrink,
  'change-picture': ImageUp,
  reset: RotateCcw,
  border: Square,
  layout: LayoutPanelTop,
  'alt-text': ScanText,
  crop: Crop,
  'edit-shape': Spline,
  fill: PaintBucket,
  'text-fill': Baseline,
  'text-outline': TypeOutline,
  'align-text': AlignVerticalJustifyCenter,
  'create-link': Link2,
  'document-info': FileText,
  'go-to-header': ArrowUpToLine,
  'go-to-footer': ArrowDownToLine,
  'link-to-previous': Link,
  'different-first-page': FileSymlink,
  'different-odd-even': BookOpen,
  'show-document-text': Eye,
  'header-from-top': ArrowUpToLine,
  'footer-from-bottom': ArrowDownToLine,
  'insert-alignment-tab': ArrowRightToLine,
  'ink-equation': PenLine,
  convert: ArrowLeftRight,
  'normal-text': Type,
  symbols: Omega,
  fraction: Divide,
  script: Superscript,
  radical: Radical,
  integral: SquareFunction,
  'large-operator': Sigma,
  bracket: Parentheses,
  function: SquareFunction,
  accent: CircleDot,
  'limit-log': InfinityIcon,
  operator: Plus,
  matrix: Grid2x2,
};

/** Overrides where one slug means different things in different tabs. */
export const ICON_BY_ID: Readonly<Record<string, IconNode>> = {
  'file.rail.close': CircleX,
  'home.editing.select': TextCursor,
  'draw.drawing-tools.select': MousePointer2,
  'table-layout.table.select': Grid2x2Check,
  'layout.page-setup.size': RulerDimensionLine,
  'layout.page-setup.columns': Columns2,
  'header-footer.close.close': CircleX,
  'header-footer.navigation.previous': ArrowLeft,
  'header-footer.navigation.next': ArrowRight,
  'table-layout.rows-columns.delete': Trash,
  'table-layout.data.sort': ArrowDownAZ,
  'picture-format.picture-styles.layout': LayoutPanelTop,
  'table-layout.draw.draw-table': PencilRuler,
  'view.zoom.page-width': MoveHorizontal,
  'shape-format.shape-styles.outline': PenLine,
  'view.views.outline': ListCollapse,
  'table-design.table-styles.gallery': Table2,
  'picture-format.picture-styles.gallery': Image,
  'shape-format.shape-styles.gallery': Shapes,
  'shape-format.wordart-styles.gallery': WandSparkles,
  'table-design.borders.borders': SquareDashed,
  'table-layout.table.properties': TableProperties,
  'table-layout.draw.eraser': Eraser,
  'shape-format.insert-shapes.text-box': TextCursorInput,
};

/** Commands that intentionally have no icon (fields and text buttons). */
export const TEXT_ONLY: ReadonlySet<string> = new Set([
  'home.font.font',
  'home.font.size',
  'view.zoom.zoom-100',
]);

/** Icon for a command id, or undefined for text-only commands. */
export function iconFor(id: string): IconNode | undefined {
  if (TEXT_ONLY.has(id)) return undefined;
  return ICON_BY_ID[id] ?? ICON_BY_SLUG[id.slice(id.lastIndexOf('.') + 1)];
}
